name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP environment
              uses: shivammathur/setup-php@v2
            - name: Install dependencies
              run: composer install --ignore-platform-reqs
            - name: PHPCSFixer check
              run: composer check-style
    phpunit:
        strategy:
            matrix:
                php_version: [8.4]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP environment
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
                  coverage: xdebug
            - name: Install dependencies
              run: composer install --ignore-platform-reqs
            - name: PHPUnit check
              run: ./vendor/bin/phpunit --coverage-text